services:
  postgres:
    container_name: transaction_db
    image: postgres:14
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - transaction_network

  rabbitmq:
    container_name: transaction_rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - transaction_network

  keydb:
    container_name: transaction_keydb
    image: eqalpha/keydb:latest
    command: keydb-server --appendonly yes
    volumes:
      - ./keydb_data:/data
    ports:
      - "6379:6379"
    networks:
      - transaction_network

  app:
    container_name: transaction_app
    build:
      context: .
    env_file:
      - .env
    environment:
      - PYTHONPATH=/opt/transaction_app
    depends_on:
      - postgres
      - rabbitmq
      - keydb
    networks:
      - transaction_network

networks:
  transaction_network:
