services:
  postgres:
    container_name: fxc_db
    image: postgres:14
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - fxc_network

  rabbitmq:
    container_name: fxc_rabbitmq
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - fxc_network

  app:
    container_name: fxc_app
    build:
      context: .
    env_file:
      - .env
    environment:
      - PYTHONPATH=/opt/fxc
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - fxc_network

networks:
  fxc_network:
