version: "3.8"

services:
  postgres:
    container_name: fxc_db
    image: postgres:14
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    networks:
      - fxc_network

  app:
    container_name: fxc_app
    build:
      context: .
    env_file:
      - .env
    environment:
      - PYTHONPATH=/opt/fxc
    depends_on:
      - postgres
    networks:
      - fxc_network

networks:
  fxc_network:
